name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-2

      - name: Build and push Docker Image
        run: |
          ls -la
          docker build -t new-custom-lambda ./docker-lambda-image-custom
          docker tag new-custom-lambda:latest 277707136485.dkr.ecr.us-east-2.amazonaws.com/new-custom-lambda:latest
          docker push 277707136485.dkr.ecr.us-east-2.amazonaws.com/new-custom-lambda:latest
